import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { getCurrentEmployee, getEffectiveRoles } from "@/lib/auth";
import { logout } from "@/app/login/actions";
import { ThemeToggle } from "@/app/ThemeToggle";

const THEME_INIT_SCRIPT = `
(function () {
  try {
    var stored = localStorage.getItem("theme");
    var theme = stored || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
    document.documentElement.setAttribute("data-theme", theme);
  } catch (e) {}
})();
`;

type NavLink = { href: string; label: string };

const ALWAYS_LINKS: NavLink[] = [
  { href: "/warehouse", label: "Magazyn" },
  { href: "/pending", label: "Oczekujące" },
];

const ROLE_LINKS: Record<string, NavLink[]> = {
  intake: [
    { href: "/intake", label: "Przyjęcie" },
    { href: "/warehouse-intake", label: "Przyjęcie (magazyn)" },
  ],
  photographer: [{ href: "/photo-queue", label: "Do zdjęć" }],
  publisher: [{ href: "/drafts", label: "Szkice AI" }],
};

const ADMIN_ONLY_LINKS: NavLink[] = [
  { href: "/dashboard", label: "Dashboard" },
  { href: "/sales", label: "Sprzedaż" },
  { href: "/expenses", label: "Wydatki" },
  { href: "/statistics", label: "Statystyki" },
  { href: "/charts", label: "Wykresy" },
  { href: "/batches-archive", label: "Partie" },
  { href: "/accounts", label: "Konta" },
  { href: "/admin/employees", label: "Pracownicy" },
  { href: "/admin/login-log", label: "Historia logowań" },
];

function getNavLinks(roles: Set<string>): NavLink[] {
  if (roles.size === 0) return [];

  const links = [...ALWAYS_LINKS];
  const seen = new Set(links.map((link) => link.href));

  const roleLinkGroups = roles.has("admin")
    ? Object.values(ROLE_LINKS)
    : [...roles].map((role) => ROLE_LINKS[role] ?? []);

  for (const group of roleLinkGroups) {
    for (const link of group) {
      if (!seen.has(link.href)) {
        seen.add(link.href);
        links.push(link);
      }
    }
  }

  if (roles.has("admin")) {
    for (const link of ADMIN_ONLY_LINKS) {
      if (!seen.has(link.href)) {
        seen.add(link.href);
        links.push(link);
      }
    }
  }

  return links;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const employee = await getCurrentEmployee();
  const roles = getEffectiveRoles(employee);
  const navLinks = getNavLinks(roles);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body className="flex min-h-full flex-col bg-[var(--color-bg)] text-[var(--color-text)]">
        {employee && (
          <header className="bg-[var(--color-surface)]">
            <nav className="mx-auto flex w-full max-w-6xl flex-wrap items-center gap-4 px-6 py-3 text-sm">
              {navLinks.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className="font-medium text-[var(--color-text-muted)] transition-colors hover:text-[var(--color-text)]"
                >
                  {link.label}
                </Link>
              ))}
              <div className="ml-auto flex items-center gap-3">
                <ThemeToggle />
                <span className="text-xs text-[var(--color-text-muted)]">
                  {employee.full_name}
                </span>
                <form action={logout}>
                  <button
                    type="submit"
                    className="text-xs font-medium text-[var(--color-text-muted)] underline-offset-2 transition-colors hover:text-[var(--color-text)] hover:underline"
                  >
                    Wyloguj
                  </button>
                </form>
              </div>
            </nav>
          </header>
        )}
        {children}
      </body>
    </html>
  );
}
